In [ ]:
%load_ext autoreload
%autoreload 2

In [1]:
from lightning_module import LOfData

In [6]:
d_module = LOfData(
    mc_file='/global/cfs/cdirs/m3246/ZjetOmnifold/data/slimmed_files/WithTracks_ZjetOmnifold_May19_MGPy8FxFxRew_syst_train.root',
    data_file='/global/cfs/cdirs/m3246/ZjetOmnifold/data/slimmed_files/WithTracks_ZjetOmnifold_Aug5_PseudoDataSRew_Dec15.root',
    muon_only=True,
    batch_size=256,
    dataloader_workers=1,
    seed=42,
    testing=False
)

Loading data...


We have a fracion 0.8144455536320278 of good events in mc
We have a fracion 1.0 of good events in pseudodata
All done with data loading!
We have 1160150 MC events and 247264 pseudo data events
We have 1407414 events in total


In [7]:
# Get data loader
d_module.setup()
train_loader = d_module.train_dataloader()
val_loader = d_module.val_dataloader()

Val dataset shape:  torch.Size([281482, 3, 2])


In [8]:
# Look at the first four batches
for i, batch in enumerate(train_loader):
    if i == 4:
        break
    print(f'Batch {i+1}')
    print(batch[0][0, 0, :])
    print()

Batch 1
tensor([5.7784, 5.3884])

Batch 2
tensor([4.8464, 4.7767])

Batch 3
tensor([5.5297, 3.5116])

Batch 4
tensor([4.8641, 4.4123])



In [9]:
# Look at the first four batches
for i, batch in enumerate(val_loader):
    if i == 4:
        break
    print(f'Batch {i+1}')
    print(batch[0][0, 0, :])
    print()

Batch 1
tensor([5.9383, 3.8650])

Batch 2
tensor([5.3572, 4.0997])

Batch 3
tensor([5.1044, 4.7357])

Batch 4
tensor([5.3381, 3.8379])

