In [1]:
%load_ext autoreload
%autoreload 2

In [5]:
# Let's make sure the input distributed layer I've written works properly. Start by initializing it as a nn.module
import torch
import torch.nn as nn
from input_distributed import InputDistributed

basic_module = nn.Sequential(
    nn.Linear(2, 4, bias=False),
    nn.ReLU()
)
distributed_module = InputDistributed(basic_module)

In [6]:
# Give it a basic forward pass
x = torch.randn(10, 2, 3)
print(x)

tensor([[[-0.3704,  0.3230, -0.2510],
         [ 0.2571,  0.0366,  1.0867]],

        [[ 0.1346, -0.2673,  0.1513],
         [ 1.2297, -0.8084,  0.9472]],

        [[ 1.0421,  0.1009, -0.4200],
         [-1.4154, -1.0666, -1.6575]],

        [[-0.6900,  1.0485, -0.0784],
         [-1.5840,  0.5122,  0.5928]],

        [[-0.3785,  0.7121, -0.7113],
         [-0.1963,  1.4434, -1.1292]],

        [[ 0.0291,  0.1321,  0.2771],
         [ 0.2776, -0.3477, -1.0085]],

        [[ 1.2678,  1.0470, -0.1623],
         [ 0.5676, -0.7818, -0.4032]],

        [[ 1.9310,  0.0996,  0.5503],
         [-3.4853,  0.8919, -0.3779]],

        [[-0.6561,  0.1812,  0.6027],
         [ 0.5211,  0.2347,  0.1602]],

        [[-1.0916,  1.1527, -0.7763],
         [ 1.3314, -0.0431,  1.4324]]])


In [10]:
y = distributed_module(x)
print(y)
print(y.shape)
print(y[0,...])

tensor([[[0.0480, 0.1399, 0.6683],
         [0.1004, 0.0000, 0.0000],
         [0.0000, 0.1719, 0.0000],
         [0.0000, 0.1163, 0.0000]],

        [[0.9045, 0.0000, 0.7136],
         [0.0000, 0.6659, 0.0000],
         [0.0000, 0.3668, 0.0000],
         [0.0000, 0.4273, 0.0000]],

        [[0.0000, 0.0000, 0.0000],
         [0.1306, 0.5677, 1.2777],
         [1.5576, 0.7589, 0.8296],
         [1.4067, 0.7616, 0.9320]],

        [[0.0000, 0.7283, 0.3852],
         [1.4190, 0.0000, 0.0000],
         [0.6179, 0.3005, 0.0000],
         [0.7648, 0.1126, 0.0000]],

        [[0.0000, 1.2580, 0.0000],
         [0.3767, 0.0000, 1.1620],
         [0.0000, 0.0000, 0.3074],
         [0.0000, 0.0000, 0.4495]],

        [[0.2038, 0.0000, 0.0000],
         [0.0000, 0.1170, 0.4122],
         [0.0000, 0.3075, 0.8277],
         [0.0000, 0.2915, 0.7993]],

        [[0.8446, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.3521],
         [0.3972, 1.1461, 0.1653],
         [0.1710, 0.9826, 0.2005]],

      

In [9]:
# Now verify that I'm getting the expected results out
weight_mat = basic_module[0].weight
out1 = torch.matmul(x[0, :, 0], weight_mat.T)
out2 = torch.matmul(x[0, :, 1], weight_mat.T)
out3 = torch.matmul(x[0, :, 2], weight_mat.T)
print(out1)
print(out2)
print(out3)

tensor([ 0.0480,  0.1004, -0.3927, -0.3345], grad_fn=<SqueezeBackward4>)
tensor([ 0.1399, -0.2433,  0.1719,  0.1163], grad_fn=<SqueezeBackward4>)
tensor([ 0.6683, -0.4768, -0.8630, -0.8406], grad_fn=<SqueezeBackward4>)


Looks good!