In [2]:
from pair_embed import PairEmbed
from net_utils import *
import numpy as np
import torch

In [64]:
x = torch.rand(10, 3, 2)

In [51]:
x = x.unsqueeze(-1).repeat(1, 1, 1, 2)
print(x.shape)

torch.Size([10, 3, 2, 2])


In [52]:
print(x[0,:,:,:])

tensor([[[0.9409, 0.9409],
         [0.5295, 0.5295]],

        [[0.6541, 0.6541],
         [0.9182, 0.9182]],

        [[0.1502, 0.1502],
         [0.5709, 0.5709]]])


In [56]:
i, j = torch.tril_indices(2, 2, offset=-1)
print(i, j)

tensor([1]) tensor([0])


In [57]:
xi = x[:,:, i, j]
xj = x[:,:, j, i]

In [58]:
print(xi.shape)

torch.Size([10, 3, 1])


In [59]:
yy = pairwise_lv_fts(xi, xj, num_outputs=3)

In [60]:
print(yy.shape)
print(yy)

torch.Size([10, 3, 1])
tensor([[[-1.3356],
         [-1.0214],
         [-0.6997]],

        [[-2.6458],
         [-1.8703],
         [-0.4517]],

        [[-1.8878],
         [-0.7991],
         [-1.4938]],

        [[-2.9218],
         [-2.5020],
         [-0.2006]],

        [[-2.1996],
         [-1.1026],
         [-0.5389]],

        [[-7.2348],
         [-6.3634],
         [-0.5462]],

        [[-3.7687],
         [-1.4084],
         [-1.4180]],

        [[-4.0618],
         [-2.5705],
         [-0.8064]],

        [[-2.5326],
         [-1.6023],
         [-0.6419]],

        [[-3.0086],
         [-0.8552],
         [-2.1295]]])


In [44]:
3*(3-1)/2

3.0

In [61]:
pe = PairEmbed(3, 0, [20, 20], remove_self_pair=True, mode='sum')

In [65]:
yy = pe(x)

In [66]:
print(yy.shape)

torch.Size([10, 20, 2, 2])


In [69]:
print(yy[0,10,:,:])

tensor([[ 0.0000, -0.0798],
        [-0.0798,  0.0000]], grad_fn=<SliceBackward0>)
